apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
  namespace: arena-subgraph
data:
  HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
  HASURA_GRAPHQL_NO_OF_RETRIES: "10"
  HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: "true"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
  HASURA_GRAPHQL_DISABLE_CORS: "true"
  PORT: "8080"
