apiVersion: v1
kind: Service
metadata:
  name: hasura-service
  namespace: arena-subgraph
spec:
  type: ClusterIP
  selector:
    app: hasura
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
