apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hasura-ingress
  namespace: arena-subgraph
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "arena-subgraph-ip"
    kubernetes.io/ingress.allow-http: "true"
spec:
  tls:
    - secretName: hasura-tls
  defaultBackend:
    service:
      name: hasura-service
      port:
        number: 8080
